import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const style = `${inter.className} w-[400px] h-[400px]`;
  return (
    <html lang="en">
      <body className={style}>
        {children}
      </body>
    </html>
  );
}
